### ISSUE TITLE
Package Control Won't Download Packages. Please Help Nothing Works. 

### ISSUE THREAD

**Issue by jwolfe890** [wbond/package_control#1256] opened 2017-08-21 08:13 UTC
I've tried all the suggested solutions, such as checking if Package Control is ignored in settings, however nothing works. I enabled to the debugger and copied the console output below. I'd greatly appreciate it if anyone could provide me any insight on this issue as I've been trying to solve this for days with no luck! 

```
Unable to open /Users/john/Library/Application Support/Sublime Text 3/Packages/Default/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Babel", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://codeload.github.com/babel/babel-sublime/zip/v8.6.3.
error: Package Control

Unable to download Babel. Please view the console for more details.
reloading /Users/john/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/john/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/john/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
```

**Comment by wbond** [comment] 2017-09-12 09:26
Trying upgrading (by hand) to Package Control 3.3.0. Then follow the directions at https://packagecontrol.io/docs/troubleshooting#There_are_no_packages_available_for_installation to generate a debug log.

**Comment by jwolfe890** [comment] 2017-09-18 09:37
It's giving me this now. Seems like the same problem :/

Package Control: Error downloading repository. HTTP exception InvalidCertificateException (Host api.github.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://api.github.com/repos/CasperLaiTW/ERBAutocomplete.git%20"ERB%20Autocomplete".
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
ignored packages updated to: ["Glue", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/john/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings
Package Control: Download Debug
  URL: https://codeload.github.com/chrissimpkins/glue/zip/v0.9.5
  Timeout: 30
  Resolved IP: 192.30.253.121
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/john/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (302566 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to codeload.github.com on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/john/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Using hostname "codeload.github.com" for TLS SNI extension
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://codeload.github.com/chrissimpkins/glue/zip/v0.9.5.
error: Package Control

Unable to download Glue. Please view the console for more details.
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/john/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
no command for selector: noop:
no command for selector: noop:
no command for selector: noop:
no command for selector: noop:
no command for selector: noop:
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
ignored packages updated to: ["Glue", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://codeload.github.com/chrissimpkins/glue/zip/v0.9.5
  Timeout: 30
  Resolved IP: 192.30.253.120
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/john/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (302566 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to codeload.github.com on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/john/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Using hostname "codeload.github.com" for TLS SNI extension
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://codeload.github.com/chrissimpkins/glue/zip/v0.9.5.
error: Package Control

Unable to download Glue. Please view the console for more details.
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

**Comment by wbond** [comment] 2017-09-20 19:48
Closing since the exact same issue was opened at #1269

**Closed by wbond** 2017-09-20 19:48 UTC

**Comment by pbrumm** [comment] 2017-12-12 16:30
I think the issue is something is wrong with the generation of the 
Package Control.merged-ca-bundle

I fixed the issue by downloading the cacert.pem from here
    https://curl.haxx.se/docs/caextract.html

and copied it over that file.

    cp $HOME/Downloads/cacert.pem '$HOME/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle'

after that I was able to install the packages correctly.

**Comment by wbond** [comment] 2017-12-12 16:35
@pbrumm This suggests you don't have the root for the certificate on your machine, so it isn't included in the exported CA list. If you turn on debugging, you should see a list of every root that is exported, and then we can see if the CA cert is in that list.

**Comment by pbrumm** [comment] 2017-12-18 23:55
it does seem that i am missing a cert from the list.  I can curl the github domain fine and hit it through a browser so it doesn't seem like it is affecting my normal usage.    overriding your generated file with the mozilla  cacert.pem gets me past it.   I can look into reverting and exporting the debug list to see if that helps.
