### ISSUE TITLE
"disable_release_note" option

### ISSUE THREAD

**Issue by vanishing** [wbond/package_control#1125] opened 2016-07-07 15:26 UTC
Hi:
It would be great if this can be implemented, or if it already has been implemented, please point me to the right option. :)
It is very very distracting to open up sublimetext, start typing, then BAM something I could care less about pop up in my face and eats my keystrokes/thoughts/cookies.

I have a lot of plugins installed, so this could happen 2, 3 times in a row.

**Comment by wbond** [comment] 2016-07-29 20:07
I would probably disable automatic updates and only install when you are comfortable with notices being displayed.

I personally don't have an interest in developing this option since it prevents me as a package developer from sending important information to users.

**Comment by deathaxe** [comment] 2022-09-19 19:17
Closing as duplicate of #1231

**Closed by deathaxe** 2022-09-19 19:17 UTC
Labels: enhancement
