### ISSUE TITLE
Install Package error

### ISSUE THREAD

**Issue by zhouyi407** [wbond/package_control#1065] opened 2016-01-11 11:19 UTC
When I'm trying to install Package, I get:

Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 3000
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in E:\Sublime Text Build 3083 x64\Data\Installed Packages\Package Control.sublime-package", line 46, in run
  File "package_control.package_installer in E:\Sublime Text Build 3083 x64\Data\Installed Packages\Package Control.sublime-package", line 59, in make_package_list
  File "package_control.package_manager in E:\Sublime Text Build 3083 x64\Data\Installed Packages\Package Control.sublime-package", line 453, in list_available_packages
  File "package_control.package_manager in E:\Sublime Text Build 3083 x64\Data\Installed Packages\Package Control.sublime-package", line 371, in list_repositories
  File "package_control.providers.channel_provider in E:\Sublime Text Build 3083 x64\Data\Installed Packages\Package Control.sublime-package", line 196, in get_repositories
  File "package_control.providers.channel_provider in E:\Sublime Text Build 3083 x64\Data\Installed Packages\Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in E:\Sublime Text Build 3083 x64\Data\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in E:\Sublime Text Build 3083 x64\Data\Installed Packages\Package Control.sublime-package", line 316, in download
OSError: exception: access violation reading 0x000000A7002DC6C0

Exception in thread Thread-5:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 1142, in run
  File "package_control.download_manager in E:\Sublime Text Build 3083 x64\Data\Installed Packages\Package Control.sublime-package", line 124, in close_all_connections
  File "package_control.download_manager in E:\Sublime Text Build 3083 x64\Data\Installed Packages\Package Control.sublime-package", line 187, in close
  File "package_control.downloaders.wininet_downloader in E:\Sublime Text Build 3083 x64\Data\Installed Packages\Package Control.sublime-package", line 203, in close
AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by wbond** [comment] 2016-01-11 17:09
Duplicate of #1039

**Closed by wbond** 2016-01-11 17:09 UTC
