### ISSUE TITLE
 One or more dependencies could not be installed or updated

### ISSUE THREAD

**Issue by AndreyAlimov** [wbond/package_control#1337] opened 2018-02-24 20:23 UTC
I'm trying to install material theme( Build 3157, Windows 10) And it doesnt work. 

```
'utf-8' codec can't decode byte 0x8d in position 0: invalid start byte
Highlighting colors with gutter icons is not supported with current ImageMagick setup. Try configuring the "icon_factory setting"
Emmet: No need to update PyV8
Package Control: Installing 3 missing dependencies
Package Control: The dependency 'pygments' is not available
Package Control: The dependency 'python-markdown' is not available
Package Control: The dependency 'mdpopups' is not available
Package Control: Skipping automatic upgrade, last run at 2018-02-24 22:18:23, next run at 2018-02-24 23:18:23 or after
reloading settings Packages/User/Preferences.sublime-settings
```
Satisfy Dependencies doesn't work also http://take.ms/AgHAa

What seem to be a problem

**Comment by FichteFoll** [comment] 2018-02-24 21:02
Duplicate of #1334.

**Comment by chouleo0814** [comment] 2018-02-25 07:59
I'm having a similar issue with MarkdownPreview (Build 3154, MacOS X)
`reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'pygments' is not currently installed; installing...
Package Control: The dependency 'pygments' is not available
Package Control: The dependency 'pygments' could not be installed or updated
ignored packages updated to: ["Markdown", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings`

**Comment by wbond** [comment] 2018-02-26 21:08
Duplicate of #1334

**Closed by wbond** 2018-02-26 21:08 UTC
