### ISSUE TITLE
SublimeLinter cann't be installed

### ISSUE THREAD

**Issue by AuthorProxy** [wbond/package_control#1340] opened 2018-02-27 08:14 UTC
Portable Dev Sublime 3157 cannot find SublimeLinter at packages, cannot restore it from config and there are "Missing" label on package control site https://packagecontrol.io/packages/SublimeLinter.

https://github.com/SublimeLinter/SublimeLinter/issues/1023

**Comment by IcyPalm** [comment] 2018-02-27 08:38
Please read for existing issues before posting here. It has been posted almost everywhere.

You can find more information here:
https://github.com/wbond/package_control/issues/1334

**Comment by wbond** [comment] 2018-02-27 21:25
Duplicate of #1334

**Closed** 2018-02-27 21:25 UTC
