### ISSUE TITLE
install package throws an error , how to fix this?

### ISSUE THREAD

**Issue by linyongfu2013** [wbond/package_control#1015] opened 2015-10-16 09:38 UTC
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "./package_control/commands/install_package_command.py", line 46, in run
  File "./package_control/package_installer.py", line 59, in make_package_list
  File "./package_control/package_manager.py", line 453, in list_available_packages
  File "./package_control/package_manager.py", line 347, in list_repositories
TypeError: 'NoneType' object is unsubscriptable

**Comment by wbond** [comment] 2015-10-23 15:55
What does your Preferences > Package Settings > Package Control > Settings - User file look like?

**Comment by Revod** [comment] 2016-02-13 18:28
Using elementary OS Freya (ubuntu 14.04) and have the same problem when I open ST build 3103 get this:

DPI scale: 1
startup, version: 3103 linux x32 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /home/revod
packages path: /home/revod/.config/sublime-text-3/Packages
state path: /home/revod/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/revod/.config/sublime-text-3/Installed Packages
ignored_packages: ["Ember.js Snippets", "Vintage"]
ignoring deprecated syntax definition: Packages/Ruby on Rails snippets/HTML (Rails).tmLanguage
Unable to decode Packages/Material Theme/assets/darker/overlay_bar_horizontal.png
pre session restore time: 3.06422
startup time: 5.05555
first paint time: 5.19325
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin AutoCompleteJS.AutoCompleteJS
reloading plugin Better CoffeeScript.CoffeeScript
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin Emmet.emmet-plugin
reloading plugin Git.add
reloading plugin Git.annotate
reloading plugin Git.commit
reloading plugin Git.diff
reloading plugin Git.flow
reloading plugin Git.git
reloading plugin Git.history
reloading plugin Git.repo
reloading plugin Git.stash
reloading plugin Git.status
reloading plugin Git.statusbar
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin Javascript Beautify.jsbeautify
reloading plugin LESS.less_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin PackageSync.PackageSync
reloading plugin PxToEm.PxToEm
reloading plugin SCSS.scss_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin SublimeLinter-ruby.linter
SublimeLinter: ruby linter loaded 
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin Babel.Babel
reloading plugin Grunt.main
reloading plugin SFTP.SFTP
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
Emmet: No need to update PyV8
reloading Packages/User/PackageSync.sublime-settings
ignoring deprecated syntax definition: Packages/Ruby on Rails snippets/HTML (Rails).tmLanguage
Exception in thread Thread-6:
Traceback (most recent call last):
  File "package_control.package_manager in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 371, in list_repositories
  File "package_control.providers.channel_provider in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 196, in get_repositories
  File "package_control.providers.channel_provider in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 224, in download
Package Control.package_control.downloaders.downloader_exception.DownloaderException: <unprintable DownloaderException object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.automatic_upgrader in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 119, in run
  File "package_control.automatic_upgrader in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 249, in upgrade_packages
  File "package_control.package_renamer in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 36, in rename_packages
  File "package_control.package_manager in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 453, in list_available_packages
  File "package_control.package_manager in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 413, in list_repositories
  File "package_control.console_write in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 34, in console_write
TypeError: __str__ returned non-string (type NoneType)

**Comment by wbond** [comment] 2016-08-01 10:43
@Revod The exception you posted is fixed by 3579f96e4f762a7145145f2cebe2b7b615867bc5

**Comment by wbond** [comment] 2016-08-01 10:44
Closing since @linyongfu2013 never replied.

**Closed by wbond** 2016-08-01 10:44 UTC
Labels: bug

**Comment by GPHemsley** [comment] 2017-04-16 01:02
It seems this is caused by `"bootstrapped": true` in the user settings. Removing it and restarting allowed Package Control commands to proceed without error, at least for me.
