### ISSUE TITLE
Package control on latest sublime and macos

### ISSUE THREAD

**Issue by quietlight** [wbond/package_control#1657] opened 2023-10-22 04:20 UTC
I have been trying for weeks. I deleted the cache, deleted all plugins and user data, deleted sublime, did brew upgrade open ssl, reinstalled sublime. No errors in the console. Install package control using the menu item in tools. It does not start. same error. Very frustrating. An editor is like a partner, its all muscle memory. Please fix this problem. (the maintenance of package control needs to be paid for by sublime who are collecting licence fees, it is essential)

Traceback (most recent call last):
  File "/Users/david/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_openssl/_libcrypto_ctypes.py", line 305, in <module>
  File "./python3.3/ctypes/__init__.py", line 366, in __getattr__
  File "./python3.3/ctypes/__init__.py", line 371, in __getitem__
AttributeError: dlsym(0x7ff90c8b6cb0, EVP_PKEY_size): symbol not found

**Comment by FichteFoll** [comment] 2023-10-22 09:59
Duplicate of #1612.

**Closed by FichteFoll** 2023-10-22 09:59 UTC
