### ISSUE TITLE
Several popular packages are missing from Package Control website

### ISSUE THREAD

**Issue by konung** [wbond/package_control#1339] opened 2018-02-26 20:55 UTC
Several packages are missing from Package Control website ( and package control pallet inside ST3), even thou they are available on GitHub.  I was able to install them by cloning directly from Github onto my MacBook, but it seems like a bug. 

For example: coala  ( popular Python code analytics tool and plugin, for many languages) 
Here is the package on github: https://github.com/coala/coala-sublime/
Here it is on the package control website with a tag missing: 
![coala packages package control](https://user-images.githubusercontent.com/72493/36694690-c825554a-1b04-11e8-85f6-ae840ef2a68b.png)

![screen shot 2018-02-26 at 14 53 51](https://user-images.githubusercontent.com/72493/36694729-e6961744-1b04-11e8-8bfc-111dce48926e.png)

There are several more packages like this that I came across, but this is just the latest one. 

Thank you, for the great editor!

**Comment by wbond** [comment] 2018-02-26 21:07
Duplicate of #1334

**Closed by wbond** 2018-02-26 21:07 UTC
