### ISSUE TITLE
Package does not get updated

### ISSUE THREAD

**Issue by bitst0rm** [wbond/package_control#1648] opened 2023-07-23 10:27 UTC
My package does not get updated since two weeks ago. It is still 0.1.9 instead of 0.1.11
The statistical diagrams do not even show since 20.07.22
What could be a reason?
https://packagecontrol.io/packages/Formatter

**Comment by deathaxe** [comment] 2023-07-23 11:33
Duplicate of #1647

**Closed by deathaxe** 2023-07-23 11:33 UTC
