### ISSUE TITLE
Hanging on 'Loading repositories'. Works after complete restart in macOS Sierra.

### ISSUE THREAD

**Issue by joshuaiz** [wbond/package_control#1261] opened 2017-08-31 13:32 UTC
Hello,

This has been an ongoing issue. After a period of time, Package Control will hang at 'Loading repositories'. I've pasted my debug log below but there is nothing indicating what could be causing it.

The only workaround I've found is to do a complete restart of my machine (macOS Sierra 10.12.13). Quitting ST3 and re-opening doesn't work. Once I've restarted, I can load repos at least for a while.

I've completely removed and reinstalled Package Control and the issue still persists.

I don't have a firewall or proxy setup. Any ideas on how to resolve this?

Thanks!

```
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3126
  Package Control Version: 3.2.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02:e000:42::1
Package Control: Found previously exported CA bundle at /Users/joshua/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (297327 bytes)
Package Control: Curl Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Trying to execute command /usr/bin/curl --connect-timeout 30 -sSL --tlsv1 --dump-header /var/folders/k6/8l4y26ln64n0973s2y4sq3wm0000gn/T/tmpb63296 --user-agent 'Package Control v3.2.1' --header 'If-None-Match: "59a7a136-4b4d6"' --header 'Accept-Encoding: bzip2,gzip,deflate' --header 'If-Modified-Since: Thu, 31 Aug 2017 05:40:06 GMT' --cacert '/Users/joshua/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle' -v https://packagecontrol.io/channel_v3.json
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3126
  Package Control Version: 3.2.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02:e000:42::1
Package Control: Found previously exported CA bundle at /Users/joshua/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (297327 bytes)
Package Control: Curl Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Trying to execute command /usr/bin/curl --connect-timeout 30 -sSL --tlsv1 --dump-header /var/folders/k6/8l4y26ln64n0973s2y4sq3wm0000gn/T/tmpqu46e1 --user-agent 'Package Control v3.2.1' --header 'If-None-Match: "59a7a136-4b4d6"' --header 'Accept-Encoding: bzip2,gzip,deflate' --header 'If-Modified-Since: Thu, 31 Aug 2017 05:40:06 GMT' --cacert '/Users/joshua/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle' -v https://packagecontrol.io/channel_v3.json
```

**Comment by wbond** [comment] 2017-09-12 09:21
It looks like you have configured your machine to use curl instead of the default urllib?

**Comment by deathaxe** [comment] 2022-09-19 18:26
Duplicate of #1227

**Closed by deathaxe** 2022-09-19 18:26 UTC
