### ISSUE TITLE
macOS 10.12 (Sierra): OSError: The Trust Settings Record was corrupted.

### ISSUE THREAD

**Issue by CaptainStiggz** [wbond/package_control#1154] opened 2016-09-20 00:17 UTC
`Cmd+Shift+p -> Install Package` fails to bring up the available package list in macOS 10.12. Debug log below.

```
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3114
  Package Control Version: 3.2.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Generating new CA bundle from system keychain
Exception in thread Thread-5:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 687, in list_available_packages
  File "package_control.package_manager in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 551, in _list_available
  File "package_control.package_manager in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 450, in list_repositories
  File "package_control.providers.channel_provider in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 117, in download
  File "package_control.downloaders.urllib_downloader in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 317, in setup_opener
  File "package_control.ca_certs in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 31, in get_ca_bundle_path
  File "package_control.ca_certs in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 140, in get_system_ca_bundle_path
  File "package_control.deps.oscrypto.trust_list in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 115, in get_path
  File "package_control.deps.oscrypto._osx.trust_list in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 86, in extract_from_system
  File "package_control.deps.oscrypto._osx._security in /Users/Zach/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 50, in handle_sec_error
OSError: The Trust Settings Record was corrupted.
```

**Comment by wbond** [comment] 2016-09-20 00:29
What is the output of running the following from the macOS Terminal: `/usr/bin/security dump-trust-settings -d`?

**Comment by CaptainStiggz** [comment] 2016-09-20 00:41
`SecTrustSettingsCopyCertificates: No Trust Settings were found.`

**Comment by wbond** [comment] 2016-09-20 01:02
Do you see any errors when you run `/usr/bin/security export -k /System/Library/Keychains/SystemRootCertificates.keychain -t certs`?

**Comment by CaptainStiggz** [comment] 2016-09-20 01:04
Nope, it looks like a valid cert chain

**Comment by wbond** [comment] 2016-09-20 01:05
Yay Apple. What a wonderful error message. I hate the macOS crypto layer…

**Comment by CaptainStiggz** [comment] 2016-09-20 01:09
Maybe it's part of their "no viruses on macOS" pitch. They just make it so unworkable we can't be asked to write malware. Let me know if I can be of any help.

**Comment by wbond** [comment] 2016-09-20 01:28
If you can remove Package Control and then clone the `osx-trust-list` branch (https://github.com/wbond/package_control/tree/osx-trust-list) into `Packages/Package Control/`.

That included a debug statement that will print what trust list is failing on your machine.

Unfortunately I wasn't able to replicate the issue on my Sierra VM.

**Comment by CaptainStiggz** [comment] 2016-09-20 01:37
`Package Control: Installing 6 missing dependencies
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3114
  Package Control Version: 3.2.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Generating new CA bundle from system keychain
Exception in thread Thread-3:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/automatic_upgrader.py", line 111, in run
    self.install_missing()
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/automatic_upgrader.py", line 143, in install_missing
    if self.installer.manager.install_package(dependency, is_dependency=True):
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/package_manager.py", line 1000, in install_package
    packages = self.list_available_dependencies()
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/package_manager.py", line 671, in list_available_dependencies
    return self._list_available()[1]
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/package_manager.py", line 551, in _list_available
    repositories = self.list_repositories()
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/package_manager.py", line 450, in list_repositories
    channel_repositories = provider.get_repositories()
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/providers/channel_provider.py", line 201, in get_repositories
    self.fetch()
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/providers/channel_provider.py", line 87, in fetch
    channel_json = manager.fetch(self.channel, 'Error downloading channel.')
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/download_manager.py", line 340, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/downloaders/urllib_downloader.py", line 117, in download
    self.setup_opener(url, timeout)
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/downloaders/urllib_downloader.py", line 317, in setup_opener
    bundle_path = get_ca_bundle_path(self.settings)
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/ca_certs.py", line 31, in get_ca_bundle_path
    system_ca_bundle_path = get_system_ca_bundle_path(settings)
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/ca_certs.py", line 140, in get_system_ca_bundle_path
    trust_list.get_path(ca_bundle_dir, hours_to_cache)
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/trust_list.py", line 115, in get_path
    for cert, trust_oids, reject_oids in extract_from_system():
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/_osx/trust_list.py", line 86, in extract_from_system
    handle_sec_error(res)
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/_osx/_security.py", line 50, in handle_sec_error
    raise exception_class(output)
OSError: The Trust Settings Record was corrupted.`

**Comment by wbond** [comment] 2016-09-20 01:40
Sorry, somehow didn't push the commit. Can you pull the latest changes from the branch and try again?

**Comment by CaptainStiggz** [comment] 2016-09-20 02:12
```
Package Control: Installing 6 missing dependencies
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3114
  Package Control Version: 3.2.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Generating new CA bundle from system keychain
Exception in thread Thread-3:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/automatic_upgrader.py", line 111, in run
    self.install_missing()
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/automatic_upgrader.py", line 143, in install_missing
    if self.installer.manager.install_package(dependency, is_dependency=True):
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/package_manager.py", line 1000, in install_package
    packages = self.list_available_dependencies()
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/package_manager.py", line 671, in list_available_dependencies
    return self._list_available()[1]
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/package_manager.py", line 551, in _list_available
    repositories = self.list_repositories()
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/package_manager.py", line 450, in list_repositories
    channel_repositories = provider.get_repositories()
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/providers/channel_provider.py", line 201, in get_repositories
    self.fetch()
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/providers/channel_provider.py", line 87, in fetch
    channel_json = manager.fetch(self.channel, 'Error downloading channel.')
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/download_manager.py", line 340, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/downloaders/urllib_downloader.py", line 117, in download
    self.setup_opener(url, timeout)
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/downloaders/urllib_downloader.py", line 317, in setup_opener
    bundle_path = get_ca_bundle_path(self.settings)
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/ca_certs.py", line 31, in get_ca_bundle_path
    system_ca_bundle_path = get_system_ca_bundle_path(settings)
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/ca_certs.py", line 140, in get_system_ca_bundle_path
    trust_list.get_path(ca_bundle_dir, hours_to_cache)
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/trust_list.py", line 115, in get_path
    for cert, trust_oids, reject_oids in extract_from_system():
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/_osx/trust_list.py", line 89, in extract_from_system
    handle_sec_error(res)
  File "/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/_osx/_security.py", line 50, in handle_sec_error
    raise exception_class(output)
OSError: The Trust Settings Record was corrupted.
```

**Comment by CaptainStiggz** [comment] 2016-09-20 02:15
So I didn't see the debugging statement in Sublime console output. I added a couple debugging lines in the same file

```python
...
print('OSCRYPTO: Error with trust settings %d' % domain)
print('OSCRYPTO: Res %d' % res)
print('OSCRYPTO: errSecInvalidTrustSettings %d' % SecurityConst.errSecInvalidTrustSettings)
if res == SecurityConst.errSecNoTrustSettings:
            continue
        if res == SecurityConst.errSecInvalidTrustSettings:
            print('OSCRYPTO: Error with trust settings %d' % domain)
            continue
        handle_sec_error(res)
```

which outputs

```
Package Control: Generating new CA bundle from system keychain
OSCRYPTO: Error with trust settings 0
OSCRYPTO: Res 0
OSCRYPTO: errSecInvalidTrustSettings -25262
Exception in thread Thread-3:
Traceback (most recent call last):
```

**Comment by wbond** [comment] 2016-09-20 02:31
Alright, I put the debug in the wrong place. Derp.

Anyway, the branch should have some useful debug info now. It should print the subject info for the cert that has the error.

Hopefully from this we can determine if such an error can just be ignored.

**Comment by CaptainStiggz** [comment] 2016-09-20 02:48
Somehow it works now, nice! I just tried installing a package and it went swimmingly. I still don't see the debug messages though, looks like importing x509 was all that was needed? Black magic. I'll try rolling back just to see if it breaks again.

```
Package Control: Skipping automatic upgrade, last run at 2016-09-19 19:33:41, next run at 2016-09-19 20:33:41 or after
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3114
  Package Control Version: 3.2.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/Zach/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (266042 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/Zach/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Successfully upgraded connection to packagecontrol.io:443 with SSL Using TLSv1/SSLv3 with cipher ECDHE-RSA-AES128-SHA
  Server SSL certificate:
    subject: CN=codexns.io,O=Codex Non Sufficit LC,L=Newbury,S=Massachusetts,C=US,serialNumber=471714639,businessCategory=Private Organization,jurisdictionStateOrProvinceName=Massachusetts,jurisdictionCountryName=US
    subject alt name: packagecontrol.io, wbond.net, sublime.wbond.net, badtls.io, codexns.io, www.codexns.io
    expire date: Nov 27 23:59:59 2016 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  If-None-Match: "57e09f2e-41843"
  Connection: Keep-Alive
  User-Agent: Package Control v3.2.0
  If-Modified-Since: Tue, 20 Sep 2016 02:30:06 GMT
  Accept-Encoding: bzip2,gzip,deflate
  Host: packagecontrol.io
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Tue, 20 Sep 2016 02:34:41 GMT
  Content-Type: application/json
  Last-Modified: Tue, 20 Sep 2016 02:30:06 GMT
  Connection: keep-alive
  ETag: "57e09f2e-41843"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from /Users/Zach/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Package Control: Looking for git at: "/usr/bin/git", "/bin/git", "/usr/sbin/git", "/sbin/git", "/usr/local/git/bin/git", "/usr/local/bin/git"
Package Control: Found git at "/usr/bin/git"
Package Control: Executing /usr/bin/git symbolic-ref -q HEAD [/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control]
Package Control: Executing /usr/bin/git config --get branch.osx-trust-list.remote [/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control]
Package Control: Executing /usr/bin/git config --get branch.osx-trust-list.merge [/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control]
Package Control: Executing /usr/bin/git fetch origin [/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control]
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
Package Control: Executing /usr/bin/git log ..origin/osx-trust-list [/Users/Zach/Library/Application Support/Sublime Text 3/Packages/Package Control]
```

**Comment by CaptainStiggz** [comment] 2016-09-20 02:56
Alright, I deleted everything and reinstalled using the script at https://packagecontrol.io/installation. Working perfectly again. What was the problem?

**Comment by wbond** [comment] 2016-09-20 03:29
The certificates are cached in the Packages/User/ folder as Package Control.merged-ca-bundle and oscrypto.ca-bundle. Deleting those and then restart Sublime Text should allow you to capture the info about what certificate is having trouble.

**Comment by unRob** [comment] 2016-09-20 05:48
After the last update, I suddenly get this error on OS X 10.11.6. Deleted the mentioned file, reinstalled from bundle since the command resulted in the same error. Found this issue since it mentions `oscrypto._osx.trust_list` on the last line of the traceback, maybe they're related? 

```
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.package_cleanup in /Users/rob/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 55, in run
  File "package_control.package_manager in /Users/rob/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1996, in record_usage
  File "package_control.download_manager in /Users/rob/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /Users/rob/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 117, in download
  File "package_control.downloaders.urllib_downloader in /Users/rob/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 317, in setup_opener
  File "package_control.ca_certs in /Users/rob/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 31, in get_ca_bundle_path
  File "package_control.ca_certs in /Users/rob/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 140, in get_system_ca_bundle_path
  File "package_control.deps.oscrypto.trust_list in /Users/rob/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 115, in get_path
  File "package_control.deps.oscrypto._osx.trust_list in /Users/rob/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 121, in extract_from_system
KeyError: b'\x8e\xdc\xee (...)'
```

**Comment by wbond** [comment] 2016-09-20 12:24
@unRob @TimePPT @davidaurelio If you can install the osx-trust-list branch as instructed in https://github.com/wbond/package_control/issues/1154#issuecomment-248176627, it should resolve your issue.

Once that is confirmed I can do a new release containing those fixes.

**Comment by liaoishere** [comment] 2016-09-20 15:58
I get same error as @unRob mentioned.  Then I remove Package Control and then clone the `osx-trust-list` branch into `Packages/Package Control/`. The bug is solved. I think we need a new release containing these fixes.

**Comment by wbond** [comment] 2016-09-20 16:15
@liaoishere Yes, I have been waiting for confirmation before shipping a new version

**Comment by unRob** [comment] 2016-09-21 03:29
[This](https://github.com/wbond/package_control/issues/1154#issuecomment-248285883) somehow disabled all my packages and had to install them all again to have them work. On the bright side, I was able install them again without a hitch. Thanks for all the hard work @wbond !

**Comment by liaoishere** [comment] 2016-09-21 04:25
@wbond After upgrade my OS X 10.11.6 to macOC Sierra 10.12. This bug no more exist.

**Comment by pzgz** [comment] 2016-09-21 15:55
I am on macOS Sierra 10.12, and just upgraded to the new package control, then I am having same error now, cannot upgrade or install packages.

**Comment by pzgz** [comment] 2016-09-21 16:49
Uninstall the Package Control package and then install it from branch `osx-trust-list` as the comments above fixed the issue, thanks.

**Comment by daflair** [comment] 2016-09-21 16:50
Hi Everyone... I ran into a similar problem with build 3114 on macOS Sierra 10.12 and used the GitHub package [Above Comment](https://github.com/wbond/package_control/issues/1154#issuecomment-248176627) and this time I found that the res value is -25262 (aka errSecUnknownError).

Solution: I added the following lines in _osx/trust_list.py starting line 86 before `handle_sec_error(res)`
<pre>
if res == -25262:
    continue
</pre>
Or if you prefer define const `errSecUnknownError = -25262` in _security.py line 121 and use `if res == SecurityConst.errSecUnknownError:` instead!

Hope this helps!

**Comment by wbond** [comment] 2016-09-21 19:11
@daflair Ok, thanks for the report!

**Comment by adrianoresende** [comment] 2016-09-21 19:13
With macOS Sierra, i deleted everything and reinstalled, with branch `osx-trust-list` and work =)

**Comment by LeZuse** [comment] 2016-09-22 11:23
Concrete steps to fix the issue until a new version of PC is out:

Shutdown Sublime app and then:
```
cd ~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/
rm Package\ Control.sublime-package
cd ../Packages/
mkdir Package\ Control
cd Package\ Control/
git clone https://github.com/wbond/package_control.git .
gch osx-trust-list
```
Launch Sublime

**Comment by Kerollmops** [comment] 2016-09-22 13:00
for those who search what is `gch` it's an alias of `git checkout` 😄

**Comment by LeZuse** [comment] 2016-09-22 13:04
@Kerollmops Sorry about that, totally forgot to replace it 😅

**Comment by wbond** [comment] 2016-09-22 21:02
@daflair Hmm, where did you get the idea there is a constant named `errSecUnknownError`? Google seems to indicate [it doesn't really exist](https://www.google.com/search?q=errSecUnknownError). The value you specified (`-25262`) seems to be [`errSecInvalidTrustSettings`](https://developer.apple.com/reference/security/1542001-anonymous/errsecinvalidtrustsettings?language=objc), which was already added to the osx-trust-list branch.

**Comment by wbond** [comment] 2016-09-22 21:21
Version 3.2.1 is out now.

You may need to follow the directions at https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling, especially if you cloned via git.

**Closed by wbond** 2016-09-22 21:21 UTC
Labels: bug
