### ISSUE TITLE
Can't find many packages

### ISSUE THREAD

**Issue by willlma** [wbond/package_control#956] opened 2015-06-08 20:54 UTC
The list of packages I have in `Package Control: Install Package` is severely limited. Examples of packages I can't find: 

- [AutoFileName](https://packagecontrol.io/packages/AutoFileName)
- [Theme - Spacegray](https://packagecontrol.io/packages/Theme%20-%20Spacegray)
- [SideBarEnhancements](https://packagecontrol.io/packages/SideBarEnhancements)
- [Git​Gutter](https://packagecontrol.io/packages/GitGutter)

None of the above are or have ever been installed.

Below is the log:

    Package Control: Fetching list of available packages
      Platform: osx-x64
      Sublime Text Version: 3083
      Package Control Version: 3.0.1
    Package Control: Download Debug
      URL: https://packagecontrol.io/channel_v3.json
      Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
      Resolved IP: 50.116.33.29
      Timeout: 30
    Package Control: Urllib Debug Proxy
      http_proxy: 
      https_proxy: 
      proxy_username: 
      proxy_password: 
    Package Control: Found previously exported CA bundle at /Users/WLM/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
    Package Control: Urllib HTTPS Debug General
      Connecting to packagecontrol.io on port 443
    Package Control: Urllib HTTPS Debug General
      Connecting to packagecontrol.io on port 443
      CA certs file at /Users/WLM/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
      Successfully upgraded connection to packagecontrol.io:443 with SSL
      Using TLSv1/SSLv3 with cipher DHE-RSA-AES128-SHA
      Server SSL certificate:
        subject: CN=codexns.io,O=Codex Non Sufficit LC,L=Newbury,S=Massachusetts,C=US,serialNumber=471714639,businessCategory=Private Organization,incorporationState=Massachusetts,incorporationCountry=US
        subject alt name: dev.codexns.io, rc.codexns.io, packagecontrol.io, wbond.net, codexns.io
        expire date: Oct 29 23:59:59 2015 GMT
      Certificate validated for packagecontrol.io
    Package Control: Urllib HTTPS Debug Write
      GET /channel_v3.json HTTP/1.1
      User-Agent: Package Control v3.0.1
      Accept-Encoding: bzip2,gzip,deflate
      Host: packagecontrol.io
      Connection: Keep-Alive
    Package Control: Urllib HTTPS Debug Read
      HTTP/1.1 200 OK
      Server: nginx
      Date: Mon, 08 Jun 2015 20:40:50 GMT
      Content-Type: application/json
      Content-Length: 22642
      Last-Modified: Mon, 08 Jun 2015 19:20:02 GMT
      Connection: keep-alive
      ETag: "5575eae2-5872"
      Content-Encoding: bzip2
      Vary: Accept-Encoding
      Strict-Transport-Security: max-age=15552000
      Accept-Ranges: bytes
    Package Control: Caching https://packagecontrol.io/channel_v3.json in /Users/WLM/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
    Package Control: Urllib HTTPS Debug General
      Closing connection to packagecontrol.io on port 443 after 1 request
    Package Control: Fetching list of available packages
      Platform: osx-x64
      Sublime Text Version: 3083
      Package Control Version: 3.0.1

Would love some help figuring this out

**Comment by KindOne-** [comment] 2015-06-08 21:03
Kinda sure this is a duplicate of #955

**Closed** 2015-06-08 21:08 UTC
