### ISSUE TITLE
packagecontrol.io is down

### ISSUE THREAD

**Issue by ryan-w-moore** [wbond/package_control#1203] opened 2016-12-05 18:09 UTC
Just wanted to point out that Packageccontrol.io is down, seems march 7th of 2015 was the last time anyone else experienced this but I was wondering if anything regarding the site can be posted so we can get an idea of the current situation and when it might be resolved. Thanks.

**Comment by wbond** [comment] 2016-12-05 18:11
Yeah, the website is having issues. Some funky issue with uwsgi and nginx. I've been working on it.

**Comment by wbond** [comment] 2016-12-05 18:14
Duplicate of #1202

**Closed by wbond** 2016-12-05 18:14 UTC
