### ISSUE TITLE
No Packages available

### ISSUE THREAD

**Issue by marisbest2** [wbond/package_control#1134] opened 2016-08-15 16:01 UTC
I'm trying to install packages, but suddenly I cant. 

```
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.
```

Also

```
Package Control: Error submitting usage information. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/submit?sublime_platform=osx&package=Package+Control&package_control_version=3.1.2&version=3.1.2&operation=install&sublime_version=3114.
Package Control: Installing 1 missing dependency
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2016-08-15 11:51:00, next run at 2016-08-15 12:51:00 or after
```

I've been able to connect before on this network so I dont think its a proxy issue.

**Comment by wbond** [comment] 2016-08-15 16:54
Please provide a debug log

**Comment by marisbest2** [comment] 2016-08-15 17:27
Not sure what you want other than 
```
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.
```

**Comment by wbond** [comment] 2016-08-15 17:54
Here is the link provided when you submitted the issue: https://github.com/wbond/package_control/blob/master/contributing.md

**Comment by marisbest2** [comment] 2016-08-15 18:23
This is all it gives me:

```
startup, version: 3114 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/.../Library/Application Support/Sublime Text 3/Packages
state path: /Users/.../Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/.../Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.276746
using gpu buffer for window
startup time: 0.322339
first paint time: 0.338406
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Error submitting usage information. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/submit?sublime_platform=osx&package_control_version=3.1.2&sublime_version=3114&package=Package+Control&operation=install&version=3.1.2.
Package Control: Installing 1 missing dependency
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, bz2, is not available
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.
>>> import urllib.request,os,hashlib; h = '2915d1851351e5ee549c20394736b442' + '8bc59f460fa1548d1514676163dafc88'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
186789
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.
Package Control: No updated packages
```

**Comment by marisbest2** [comment] 2016-08-15 20:16
My bad. You're right.

```
Package Control: Download Debug
  URL: https://packagecontrol.io/submit?operation=install&package_control_version=3.1.2&package=Package+Control&sublime_platform=osx&version=3.1.2&sublime_version=3114
  Timeout: 30
  Resolved IP: 50.116.33.29
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/.../Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/.../Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
Package Control: Error submitting usage information. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/submit?operation=install&package_control_version=3.1.2&package=Package+Control&sublime_platform=osx&version=3.1.2&sublime_version=3114.
Package Control: Installing 1 missing dependency
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3114
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/.../Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, bz2, is not available
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3114
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/.../Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3114
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/.../Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.
Package Control: No updated packages

Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3114
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/.../Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/.../Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.

```

**Comment by wbond** [comment] 2016-08-15 20:19
Is the file `/Users/.../Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle` empty?

Alternatively, do you see certificate errors connecting to https://packagecontrol.io in your browser?

Do you have some sort of network device that intercepts secure network connections, that could be replacing the secure certificate with its own?

**Comment by chshouyu** [comment] 2016-11-10 09:42
#1187

**Comment by wbond** [comment] 2016-12-09 11:25
@marisbest2 I'm curious if you are still having this problem with the latest version of Package Control? There is a different certificate issues on the server now, and Package Control 3.2.1 has some enhancements that may help in debugging the issue.

**Comment by wbond** [comment] 2017-09-12 15:15
Please try upgrading to Package Control 3.3.0. This should hopefully resolve the invalid certificate error.

**Comment by fabritw** [comment] 2017-09-22 23:54
I encountered the same SSL certificate error on OSX (using Sublime Text 3 / Package Control 3.3.0). 
My solution was to change the "downloader_precedence" settings to replace urllib with curl:

`"downloader_precedence": {
    "osx": ["curl"]
},`

**Comment by dendy77** [comment] 2017-10-05 07:50
Hello .. i have same problem here .. Running MacOS High Sierra, latest version of Sublime 3 and Package Control (3.3.0)

With default configuration i get after "Install package" this error in console:

Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.

(but if i open that json url in web browser directly, certificate is OK, valid)

When i try set "downloader_precedence" like fabritw mentioned, i get error :

Package Control: Error downloading channel. } [512 bytes data] } [2 bytes data] curl: (60) SSL certificate problem: certificate not trusted More details here: https://curl.haxx.se/docs/sslcerts.html curl performs SSL certificate verification by default, using a "bundle"  of Certificate Authority (CA) public keys (CA certs). If the default  bundle file isn't adequate, you can specify an alternate file  using the --cacert option. If this HTTPS server uses a certificate signed by a CA represented in  the bundle, the certificate verification probably failed due to a  problem with the certificate (it might be expired, or the name might  not match the domain name in the URL). If you'd like to turn off curl's verification of the certificate, use  the -k (or --insecure) option. HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure. downloading https://packagecontrol.io/channel_v3.json.

**Comment by dwasss** [comment] 2018-06-07 21:48
I can confirm following the steps in https://github.com/wbond/package_control/issues/1302#issuecomment-352076439 (basically deleting anything Package Control related and installing the prerelease version) I was able to finally get it to work and install packages.

**Comment by deathaxe** [comment] 2022-09-25 10:25
Closing with regards to #1302 as this error was most likely caused by encoding issues in asn1crypto.

**Closed by deathaxe** 2022-09-25 10:25 UTC
Labels: TLS
