### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by Totn** [wbond/package_control#1040] opened 2015-12-18 03:58 UTC
what have done:  uninstall sublime text 3 (3083); and then reinstall the sublime;
after install the package control, when I try to install package, the console show this:

<pre>
{'folders': [{'path': 'D:\\www\\piao'}]}
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Exception in thread Thread-9:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in C:\Users\Totn\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 46, in run
  File "package_control.package_installer in C:\Users\Totn\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 59, in make_package_list
  File "package_control.package_manager in C:\Users\Totn\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 453, in list_available_packages
  File "package_control.package_manager in C:\Users\Totn\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 371, in list_repositories
  File "package_control.providers.channel_provider in C:\Users\Totn\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 196, in get_repositories
  File "package_control.providers.channel_provider in C:\Users\Totn\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in C:\Users\Totn\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Users\Totn\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 316, in download
OSError: exception: access violation reading 0x000001F400007530

Exception in thread Thread-10:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 1142, in run
  File "package_control.download_manager in C:\Users\Totn\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 124, in close_all_connections
  File "package_control.download_manager in C:\Users\Totn\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 187, in close
  File "package_control.downloaders.wininet_downloader in C:\Users\Totn\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 203, in close
AttributeError: 'NoneType' object has no attribute 'upper'
</pre>

**Comment by wbond** [comment] 2015-12-18 04:03
Looks like a duplicate of #1039

**Closed by wbond** 2015-12-18 04:03 UTC
