### ISSUE TITLE
Package Control Not Listing All Available Packages

### ISSUE THREAD

**Issue by laidbackwebsage** [wbond/package_control#1360] opened 2018-05-12 11:47 UTC
1. Ctrl-Shift-p
2. Package Control: Install Package; Enter
3. Type in "Bootstrap 4 Autocomplete"
4. Nothing appears.

Package is here: https://packagecontrol.io/packages/Bootstrap%204%20Autocomplete

This has happened with other packages, as well.

Version is 3.0, Build 3170. Installed via ppa on Ubuntu Budgie 18.04. Fully registered.

I have already removed and re-installed Package Control, as well as Sublime Text 3.

Please don't tell me to install it manually. Ain't nobody got time for that, and things should work they way they are supposed to work. Something is broken and it needs to fixed, not patched.  :-)

Many thanks for any help!

**Comment by Unknow0059** [comment] 2019-08-31 15:29
I have this issue as well, but with more than one package. 
Rather, they are listed in the List Packages, but they are nowhere to be found in Package Settings (even if they have their own settings files, which I can edit with Resource Viewer).

**Comment by deathaxe** [comment] 2023-11-26 18:09
Closing as duplicate of #1557.

Packages marked missing or under review are not published via channel.json. Thus Package Control client doesn't see them as available.

**Closed by deathaxe** 2023-11-26 18:09 UTC
