### ISSUE TITLE
Package Control isnt working

### ISSUE THREAD

**Issue by debdebbie** [wbond/package_control#1620] opened 2022-07-02 04:00 UTC
Hi, my package control isnt working, you can check with the screenshot
![Screenshot 2022-07-02 at 11 57 26](https://user-images.githubusercontent.com/78006918/176985752-826c7c27-45ad-4767-883d-72ba268cbd28.png)
![Screenshot 2022-07-02 at 11 59 34](https://user-images.githubusercontent.com/78006918/176985756-d1ec791f-2339-4973-8295-5d68b6d8dcb0.png)
![Screenshot 2022-07-02 at 12 01 27](https://user-images.githubusercontent.com/78006918/176985782-3f92efd5-5c8d-407b-af7b-ce8c803b332c.png)

**Comment by debdebbie** [comment] 2022-07-02 04:01
![Screenshot 2022-07-02 at 12 00 57](https://user-images.githubusercontent.com/78006918/176985767-5e94b895-1ae6-42b6-971c-6b15145574de.png)

**Comment by deathaxe** [comment] 2022-07-02 09:22
Maybe have a look at https://github.com/wbond/package_control/issues/1612. Package Control requires OpenSSL 1.1, while recent MacOS versions seem to ship OpenSSL 3 only.

**Comment by debdebbie** [comment] 2022-07-02 11:28
> Maybe have a look at #1612. Package Control requires OpenSSL 1.1, while recent MacOS versions seem to ship OpenSSL 3 only.

I installed the OpenSSL 3, but it still not works

**Comment by FichteFoll** [comment] 2022-07-02 12:48
You need 1.1.

**Comment by FichteFoll** [comment] 2022-07-02 12:54
You need 1.1.
What's the version of your OS so that we can check whether it is indeed the same issue as #1612? Also, please share the contents of your console (*View → Console*) after starting ST with PC installed.

**Comment by deathaxe** [comment] 2022-08-14 21:11
I may be missing something, but IIRC, Sublime Text supports python-3.8 plugin-host when run natively on Apple Silicon only, because python 3.3 it too old to be compiled for arm64.

Package Control 3.4 however runs on python 3.3 only. So it is available only when running ST via rosetta. Same applies for plugins which require dependencies.

**Comment by rchl** [comment] 2022-08-15 05:31
3.3 host is natively compiled for Apple silicon. ST devs applied patches that made it compile.

**Comment by ondohotola** [comment] 2023-07-10 19:49
Since openssl 3 is required by a number of tools such as for example `wget` and openssl 1.1 by some others for example emacs I ran

```bash
brew unlink openssl@3
brew unlink openssl@1.1
```

on my Intel Macs which removed the symlinks in /usr/local/lib but keeps them installed, and now Package Control works as advertized again.

**Comment by deathaxe** [comment] 2023-08-02 08:25
Duplicate of #1612

**Closed by deathaxe** 2023-08-02 08:25 UTC
Labels: duplicate

**Comment by YakultGo** [comment] 2023-09-30 15:56
I meet the same problem, now 

> Since openssl 3 is required by a number of tools such as for example `wget` and openssl 1.1 by some others for example emacs I ran
> 
> ```shell
> brew unlink openssl@3
> brew unlink openssl@1.1
> ```
> 
> on my Intel Macs which removed the symlinks in /usr/local/lib but keeps them installed, and now Package Control works as advertized again.

thank you, have solved
