### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER downloading https://packagecontrol.io/channel_v3.json

### ISSUE THREAD

**Issue by nralbers** [wbond/package_control#1350] opened 2018-03-20 14:00 UTC
## Situation
In a corporate environment with a proxy that rewrites SSL connections. Machine is configured with a local squid proxy that uses kerberos to authenticate against the remote kerberos proxy. 

## Steps taken

- added http_proxy and https_proxy settings to packagecontrol user settings file.
- added corporate ca-certificate to Package Control.user-ca-bundle
- tested connection to https://packagecontrol.io using curl and passing the same ca-certificate Using the package list json url supplies the correct content when using curl.

## Error
Fails to download package list with a SSL: WRONG_VERSION_NUMBER error

## Debug Log
startup, version: 3143 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/xwing/.config/sublime-text-3/Packages
state path: /home/xwing/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/xwing/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.072901
startup time: 0.120458
first paint time: 0.126254
Unable to fetch update url contents
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2018-03-20 13:29:00, next run at 2018-03-20 14:29:00 or after
Package Control: Fetching list of available packages and dependencies
  Platform: linux-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: [Errno -2] Name or service not known
Package Control: Urllib Debug Proxy
  http_proxy: http://localhost:3128
  https_proxy: http://localhost:3128
  proxy_username: 
  proxy_password: 
Package Control: Found system CA bundle at /usr/lib/ssl/certs/ca-certificates.crt (261407 bytes)
Package Control: Regenerated the merged CA bundle from the system and user CA bundles
Package Control: Urllib HTTPS Debug General
  Connecting to localhost on port 3128
Package Control: Urllib HTTPS Debug Write
  CONNECT packagecontrol.io:443 HTTP/1.1
  User-Agent: Package Control v3.3.0
  Proxy-Connection: Keep-Alive
  Host: packagecontrol.io:443
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 Connection established
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /home/xwing/.config/sublime-text-3/Packages/User/Package Control.merged-ca-bundle
  Using hostname "packagecontrol.io" for TLS SNI extension
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host localhost:3128 returned an invalid certificate ([SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.
Unable to open /home/xwing/.config/sublime-text-3/Packages/Package Control/Package Control.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Fetching list of available packages and dependencies
  Platform: linux-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: [Errno -2] Name or service not known
Package Control: Urllib Debug Proxy
  http_proxy: localhost:3128
  https_proxy: localhost:3128
  proxy_username: 
  proxy_password: 
Package Control: Found system CA bundle at /usr/lib/ssl/certs/ca-certificates.crt (261407 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to localhost on port 3128
Package Control: Urllib HTTPS Debug Write
  CONNECT packagecontrol.io:443 HTTP/1.1
  User-Agent: Package Control v3.3.0
  Proxy-Connection: Keep-Alive
  Host: packagecontrol.io:443
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 Connection established
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /home/xwing/.config/sublime-text-3/Packages/User/Package Control.merged-ca-bundle
  Using hostname "packagecontrol.io" for TLS SNI extension
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host localhost:3128 returned an invalid certificate ([SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.

**Comment by dwasss** [comment] 2018-06-07 22:02
It looks like the local proxy you're going through has some SSL/TLS issues in that perhaps it supports older versions of SSL/TLS but your Package Control client only wants to use newer versions. Not sure though...

**Comment by deathaxe** [comment] 2022-10-07 16:47
Closing with regards to #1302 as this error was most likely caused by encoding issues in asn1crypto.

**Closed by deathaxe** 2022-10-07 16:47 UTC
