### ISSUE TITLE
constant "1 missing dependency was just installed" pop-up

### ISSUE THREAD

**Issue by demon386** [wbond/package_control#1130] opened 2016-07-29 10:10 UTC
I pop-up everytime I launch Sublime. Log:

```
Package Syncing: Start Complete Sync
Package Syncing: Already running
Package Syncing: End Complete Sync
Package Control: Installing 1 missing dependency
/Users/tongmuchenxuan/Library/Application Support/Sublime Text 3
LOADING BOOKMARKS
/Users/tongmuchenxuan/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/loader.py:197: UserWarning: Duplicate name: '51-python-jinja2.py'
Package Control: Installed missing dependency python-jinja2
Package Control: Skipping automatic upgrade, last run at 2016-07-29 17:50:46, next run at 2016-07-29 18:50:46 or after
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
```

**Comment by wbond** [comment] 2016-08-04 09:15
You'll have to provide a more complete log, with the `debug` setting set to `true`.

It seems somehow your environment has gotten to a point where `python-jinja2` is installed, but Package Control doesn't think it is.

**Comment by FichteFoll** [comment] 2016-08-04 12:27
Pretty sure this is a duplicate of #989.

**Comment by wbond** [comment] 2016-09-13 15:01
I've made some fixes recently that should fix this. The following commits should help:

 - 0cd0b47f5c2254bf969081edf52bdaba834d04b6
 - c6a7faa42a2c32af2cfe9f3db7411f94d8f52971
 - e8b1001bc9cf403312e83a074f330fbd6623a557

**Closed by wbond** 2016-09-13 15:01 UTC
Labels: bug, dependencies
