### ISSUE TITLE
Package Control on OSX 10.6.8?

### ISSUE THREAD

**Issue by NealeTools** [wbond/package_control#1175] opened 2016-10-12 15:30 UTC
I have installed (or think I have installed) Package Control into Sublime Text 2 on OSX 10.6.8, using these instructions: https://packagecontrol.io/installation#st2
Certainly it has been added to the packages folder.
However, I am unable to use the Command Palette to access any new features/commands.
If I start typing Package Control, the only options are: Settings-default and Settings-User
The User file is blank.
I'm really not sure if I am doing something wrong or if there is a bug.

Here is the console log:

startup, version: 2221 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/mattneale/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/mattneale/Library/Application Support/Sublime Text 2/Settings
PackageSetup not required
catalogue loaded
found 5 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/CSS/css_completions.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/open_in_browser.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Package Control/1_reloader.py
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Package Control/2_bootstrap.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./2_bootstrap.py", line 22, in <module>
    from package_control.bootstrap import bootstrap_dependency, mark_bootstrapped
  File "./package_control/bootstrap.py", line 20, in <module>
    from .download_manager import downloader
  File "./package_control/download_manager.py", line 24, in <module>
    from .downloaders import DOWNLOADERS
  File "./package_control/downloaders/__init__.py", line 3, in <module>
    from .urllib_downloader import UrlLibDownloader
  File "./package_control/downloaders/urllib_downloader.py", line 46, in <module>
    from ..ca_certs import get_ca_bundle_path
  File "./package_control/ca_certs.py", line 7, in <module>
    from .deps.oscrypto import trust_list
  File "./package_control/deps/oscrypto/trust_list.py", line 19, in <module>
    from ._osx.trust_list import extract_from_system, system_path
  File "./package_control/deps/oscrypto/_osx/trust_list.py", line 9, in <module>
    from ._security import Security, SecurityConst, handle_sec_error
  File "./package_control/deps/oscrypto/_osx/_security.py", line 10, in <module>
    from ._security_ctypes import Security, version_info as osx_version_info
  File "./package_control/deps/oscrypto/_osx/_security_ctypes.py", line 24, in <module>
    raise OSError('Only OS X 10.7 and newer are supported, not %s.%s' % (version_info[0], version_info[1]))
OSError: Only OS X 10.7 and newer are supported, not 10.6
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Package Control/Package Control.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./Package Control.py", line 95, in <module>
    from package_control.commands import *  # noqa
  File "./package_control/commands/__init__.py", line 3, in <module>
    from .advanced_install_package_command import AdvancedInstallPackageCommand
  File "./package_control/commands/advanced_install_package_command.py", line 10, in <module>
    from ..package_manager import PackageManager
  File "./package_control/package_manager.py", line 34, in <module>
    from .downloaders.background_downloader import BackgroundDownloader
  File "./package_control/downloaders/__init__.py", line 3, in <module>
    from .urllib_downloader import UrlLibDownloader
  File "./package_control/downloaders/urllib_downloader.py", line 46, in <module>
    from ..ca_certs import get_ca_bundle_path
  File "./package_control/ca_certs.py", line 7, in <module>
    from .deps.oscrypto import trust_list
  File "./package_control/deps/oscrypto/trust_list.py", line 19, in <module>
    from ._osx.trust_list import extract_from_system, system_path
  File "./package_control/deps/oscrypto/_osx/trust_list.py", line 9, in <module>
    from ._security import Security, SecurityConst, handle_sec_error
  File "./package_control/deps/oscrypto/_osx/_security.py", line 10, in <module>
    from ._security_ctypes import Security, version_info as osx_version_info
  File "./package_control/deps/oscrypto/_osx/_security_ctypes.py", line 24, in <module>
    raise OSError('Only OS X 10.7 and newer are supported, not %s.%s' % (version_info[0], version_info[1]))
OSError: Only OS X 10.7 and newer are supported, not 10.6
Reloading plugin /Users/mattneale/Library/Application Support/Sublime Text 2/Packages/Rtools-master/Rtools.py
plugin init time: 0.130076
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.254398
using gamma: 1 (err: 0)
startup cache, total files: 97 cache hits: 97
startup time: 0.353109 (package setup was not run)
loaded 837 snippets

**Comment by wbond** [comment] 2016-10-12 17:01
This is a duplicate of #1162.

Unfortunately the recent security enhancements don't support OS X 10.6 because there are significant changes in the OS X Security.framework between 10.6 and 10.7. I don't have time to try to see if there are workarounds for such an old OS.

If you are interested in seeing support for this added, you would need to dive into https://github.com/wbond/oscrypto and figure out all of the alternative APIs that would be required for 10.6. Here is the primary API definitions for ctypes that outlines what functions are currently used: https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/_security_ctypes.py.

The alternative would be to start some crowdfunding to pay me to do such a thing.

**Closed by wbond** 2016-10-12 17:01 UTC
