### ISSUE TITLE
Package install message scrolled out

### ISSUE THREAD

**Issue by Suor** [wbond/package_control#886] opened 2015-02-21 13:07 UTC
When I install a package I get "Package Control Messages" buffer scrolled all the way down, so that I can only see last, usually empty, line of a message. Happens both on ST2 and 3.

![install-message-fail](https://cloud.githubusercontent.com/assets/284103/6314156/05ddb2f6-ba05-11e4-91ca-65663bd984bb.png)

**Comment by FichteFoll** [comment] 2015-02-28 16:30
Just had the same but I'm not sure if it happens all the time. Should be an easy fix however.

**Comment by Suor** [comment] 2015-02-28 16:44
For me it happens each time.

**Comment by Suor** [comment] 2015-02-28 16:46
If I could help track this down let me know. I could probably run some debugging code or so.

**Comment by FichteFoll** [comment] 2015-02-28 16:55
Since it happened for me (and I have an approximate idea of what's going wrong) there shouldn't be a problem with his, but I'll come back to you if I do need your environment. Thanks for the offer.

**Comment by FichteFoll** [comment] 2015-03-02 03:38
After staring at the code finding to spot the error and then ~~some~~ comperatively a lot of fiddling I believe this to be a sublime bug.

The following code defines a command with a stripped-down version of the code that writes the update messages.

What happens when you run the `test_command` command n times:

1. New view opens, view is scrolled to bottom
2. Text is appended and also scrolled to bottom
3. and following: Text is appended but not scrolled anymore. Only adjusts if it would exceed the view.

If anyone can confirm this I will open a bug report on the ST issue tracker. This makes no sense to me.

```py
import sublime
import sublime_plugin

output = """

Test yo
-------

    Some completely irrelevant text
    that also happens
    to have a few line breaks
    and is indented
    somewhat.
"""


class TestCommandCommand(sublime_plugin.WindowCommand):
    def run(self):
        window = sublime.active_window()

        views = window.views()
        view = None
        for _view in views:
            if _view.name() == 'Package Control Messages':
                view = _view
                break

        if not view:
            view = window.new_file()
            view.set_name('Package Control Messages')
            view.set_scratch(True)
            view.settings().set("word_wrap", True)
            view.settings().set("auto_indent", False)
        # else:
            # view.set_read_only(False)
            # if window.active_view() != view:
            #     window.focus_view(view)

        def write(string):
            view.run_command('insert', {'characters': string})

        # if not view.size():
        #     write('Package Control Messages\n'
        #           '========================')

        # position = view.size()
        # view.sel().clear()
        # view.sel().add(sublime.Region(position, position))
        write(output)
        # print(position, view.size())

        # view.show(0)
        # view.show(position)
        # view.set_read_only(True)
```

**Comment by FichteFoll** [comment] 2015-03-02 03:49
Now, to the interesting part: If you change things around a bit (especially when uncommenting `view.show(position)` and the `position = view.size()` definition it starts to work properly, but when you uncomment the `if not view.size():` part it suddenly only scrolls at any following call but NOT the initial one. I am **completely** at lost why this is the case.

```py
import sublime
import sublime_plugin

output = """

Test yo
-------

    Some completely irrelevant text
    that also happens
    to have a few line breaks
    and is indented
    somewhat.
"""


class TestCommandCommand(sublime_plugin.WindowCommand):
    def run(self):
        window = sublime.active_window()

        views = window.views()
        view = None
        for _view in views:
            if _view.name() == 'Package Control Messages':
                view = _view
                break

        if not view:
            view = window.new_file()
            view.set_name('Package Control Messages')
            view.set_scratch(True)
            view.settings().set("word_wrap", True)
            view.settings().set("auto_indent", False)
        else:
            view.set_read_only(False)
            if window.active_view() != view:
                window.focus_view(view)

        def write(string):
            view.run_command('insert', {'characters': string})

        if not view.size():
            write('Package Control Messages\n'
                  '========================')

        position = view.size()
        view.sel().clear()
        view.sel().add(sublime.Region(position, position))
        write(output)

        view.show(position)
        view.set_read_only(True)
```

I'll just go to bed :weary:

**Comment by Suor** [comment] 2015-03-02 04:45
There is an easy work-around: move `position = view.size()` before writing "Package Control Messages", you probably want this anyway, cause why do you want a header that nobody sees?

The thing is a bug only shows up when it's a new buffer and `position` is greater than zero. So for reused buffer this will just work and for new one you just start at top.

**Comment by Suor** [comment] 2015-03-02 04:52
P.S. it is definitely a bug, I can easily reproduce it in ST3, build 3065. `view.show()` acts like line lengths are not updated according to new text.

P.P.S. A side thought. Maybe always using a new buffer is ok, why do you mess with that buffer reuse? In case I get several messages at once it appears that current code will scroll so that I will see only last one, which is a fail. And if it's a separate message it will effectively scroll out previous one I probably not read yet.

**Comment by FichteFoll** [comment] 2015-03-02 13:58
> In case I get several messages at once it appears that current code will scroll so that I will see only last one, which is a fail.

You are correct, it will show the start of the latest new package message in center. I thought that the function is only called once for each update batch but it's called for each package in which case we should probably just preserve the viewport.

Jon said he couldn't reproduce it so it could be an issue with a plugin. I don't think I have a plugin installed that messes with scrolling though. Will test on a fresh portable install.

**Comment by FichteFoll** [comment] 2015-03-02 14:51
Created a thread on the forum regarding this bug, hopefully Jon can reproduce this now and fix.
http://www.sublimetext.com/forum/viewtopic.php?f=3&t=17677

In the mean time I will try a different method for the update messages.

**Comment by Suor** [comment] 2015-03-02 14:56
You can try my workaround, it should work.

**Comment by FichteFoll** [comment] 2015-03-02 15:12
Your work around will result in the "pakcage control messages\n=====" header being appended instead of prepended since the selection is being changed to assure that the new message is always. I'm also solving the scroll issue currently, but this scroll bug appears everywhere, even when using view.set_viewport_position. I'll probably have to use a 90% working solution

**Comment by Suor** [comment] 2015-03-02 15:16
Ok, try this: use current method if view is old, use `view.show(0)` after
inserting to new one.

**Comment by FichteFoll** [comment] 2015-03-03 03:36
FWIW, the bug is going to be fixed in the next ST build. My pull request is still an enhancement though because it preserves the previous viewport instead of scrolling to the start of the latest message.

**Closed** 2015-03-13 05:09 UTC
Labels: bug
