### ISSUE TITLE
There are no packages available for installation

### ISSUE THREAD

**Issue by xlong88** [wbond/package_control#1051] opened 2016-01-03 12:19 UTC
Package Control: Download Debug
  URL: https://packagecontrol.io/submit?package_control_version=3.1.2&sublime_platform=osx&package=Package+Control&sublime_version=2221&version=3.1.2&operation=install
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/longgong/Library/Application Support/Sublime Text 2/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/longgong/Library/Application Support/Sublime Text 2/Packages/User/Package Control.merged-ca-bundle
  Successfully upgraded connection to packagecontrol.io:443 with SSL Using TLSv1/SSLv3 with cipher DHE-RSA-AES128-SHA
  Server SSL certificate:
    subject: CN=codexns.io,O=Codex Non Sufficit LC,L=Newbury,S=Massachusetts,C=US,serialNumber=471714639,businessCategory=Private Organization,incorporationState=Massachusetts,incorporationCountry=US
    subject alt name: codexns.com, packagecontrol.io, wbond.net, rc.codexns.io, codexns.io, www.codexns.io
    expire date: Nov 27 23:59:59 2016 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /submit?package_control_version=3.1.2&sublime_platform=osx&package=Package+Control&sublime_version=2221&version=3.1.2&operation=install HTTP/1.1
  Host: packagecontrol.io
  Connection: Keep-Alive
  Accept-Encoding: bzip2,gzip,deflate
  User-Agent: Package Control v3.1.2
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Sun, 03 Jan 2016 12:16:53 GMT
  Content-Type: application/json
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  X-App-Version: 1.3.3
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
Package Control: Installing 1 missing dependency
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 2221
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib HTTPS Debug General
  Re-using connection to packagecontrol.io on port 443 for request #2
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  Accept-Encoding: bzip2,gzip,deflate
  Connection: Keep-Alive
  User-Agent: Package Control v3.1.2
  Host: packagecontrol.io
  If-Modified-Since: Sun, 03 Jan 2016 12:00:01 GMT
  If-None-Match: "56890d41-6a"
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Sun, 03 Jan 2016 12:16:53 GMT
  Content-Type: application/json
  Content-Length: 113
  Last-Modified: Sun, 03 Jan 2016 12:10:01 GMT
  Connection: keep-alive
  ETag: "56890f99-71"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
  Accept-Ranges: bytes
Package Control: Caching https://packagecontrol.io/channel_v3.json in /Users/longgong/Library/Application Support/Sublime Text 2/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2016-01-03 06:31:23, next run at 2016-01-03 07:31:23 or after
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 2 requests
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 2221
  Package Control Version: 3.1.2
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 2221
  Package Control Version: 3.1.2
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 2221
  Package Control Version: 3.1.2

**Comment by wbond** [comment] 2016-01-03 12:39
Duplicate of #1049.

**Closed by wbond** 2016-01-03 12:39 UTC
