### ISSUE TITLE
Package Control is not working

### ISSUE THREAD

**Issue by debdebbie** [wbond/package_control#1522] opened 2021-02-02 13:42 UTC
Package Control can't install anything.
Even I check the preferences-package settings-package control-empty(default, user, settings).
And also the try looks out the Preference: Browse Package - User - Empty.

Anyone face the same issues before?

**Comment by wbond** [comment] 2021-02-02 13:44
Please post your ST console contents.

**Comment by debdebbie** [comment] 2021-02-02 13:48
> Please post your ST console contents.

I only tried typing "Package Control: List Packages" but at my end, it shows the same wording "Package Control: List Packages"

**Comment by wbond** [comment] 2021-02-02 14:01
Use the View > Show Console menu to display the console and then paste the contents here.

**Comment by debdebbie** [comment] 2021-02-02 14:02
> Use the View > Show Console menu to display the console and then paste the contents here.

using gpu buffer for window

**Comment by wbond** [comment] 2021-02-02 14:07
Try starting ST fresh and get the contents of the first window. There should be around 50-100 lines present after a fresh start.

**Comment by debdebbie** [comment] 2021-02-02 14:12
> Try starting ST fresh and get the contents of the first window. There should be around 50-100 lines present after a fresh start.

can I know what words should type in for fresh start?

**Comment by wbond** [comment] 2021-02-02 14:26
Completely close the application and then open it again.

**Comment by debdebbie** [comment] 2021-02-02 14:29
> Completely close the application and then open it again.

Thank you, I got it now!

startup, version: 3211 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages
state path: /Users/stuartchloe/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.352123
using gpu buffer for window
startup time: 0.858504
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/2_bootstrap.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/bootstrap.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/__init__.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/oscrypto_downloader.py", line 44, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/tls.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_mac/tls.py", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_mac/util.py", line 208, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_openssl/_libcrypto.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
  File "./python3.3/ctypes/__init__.py", line 353, in __init__
OSError: dlopen(/Users/stuartchloe/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
	/Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
	/Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
reloading plugin Package Control.Package Control
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/Package Control.py", line 89, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/commands/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/commands/advanced_install_package_command.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/__init__.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/oscrypto_downloader.py", line 44, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/tls.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_mac/tls.py", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_mac/util.py", line 208, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_openssl/_libcrypto.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
  File "./python3.3/ctypes/__init__.py", line 353, in __init__
OSError: dlopen(/Users/stuartchloe/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
	/Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
	/Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
plugins loaded

**Comment by deathaxe** [comment] 2021-02-02 16:06
> OSError: dlopen(/Users/stuartchloe/lib/libcrypto.dylib, 6): no suitable image found. Did find:
> /Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
> /Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture

Appears to be the same issue as #1519

**Comment by wbond** [comment] 2021-02-02 16:11
Can you give a info about your machine @debdebbie?

 - Is this an Intel Mac, or one of the new M1s?
 - Did you upgrade an old OS to a new one, or transfer your files in some way?

This is the third time I've seen this issue, which means it has been happening to other users also.

My hunch is that it has something to do with Rosetta 2 and the mix of Sublime Text running as x64 and the lib being arm64.

**Comment by mugurm** [comment] 2021-02-02 18:00
I believe I have the same issue. I'm on an Intel Macbook Pro with Big Sur 11.1

Console output: 

startup, version: 3211 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/mugurmarculescu/Library/Application Support/Sublime Text 3/Packages
state path: /Users/mugurmarculescu/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/mugurmarculescu/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Package Control", "Vintage"]
pre session restore time: 0.339121
using gpu buffer for window
startup time: 0.724986
git: tracking working dir /Users/mugurmarculescu/mbox/git/mugurcom-node
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
reloading plugin Babel.Babel
reloading plugin ColorPicker.sublimecp
reloading plugin JavaScript Completions._generated_2018_02_11_at_20_21_24
reloading plugin JavaScript Completions.reloader
plugins loaded
no command for selector: noop:

**Comment by wbond** [comment] 2021-02-02 18:02
@mugurm In your situation you have "Package Control" in your ignored_packages setting.

**Comment by mugurm** [comment] 2021-02-02 18:04
@wbond thanks, will look into that, thought it should be noted I did not attempt to ignore the package, nor played around with moving files so not sure why that's the case.

**Comment by wbond** [comment] 2021-02-02 18:05
It can happen if Package Control tries to update itself and Sublime Text is restarted to install an update at the same time.

**Comment by mugurm** [comment] 2021-02-02 18:06
@wbond thanks again for the super fast response. I can confirm that fixed my issue.

**Comment by debdebbie** [comment] 2021-02-03 03:08
> Can you give a info about your machine @debdebbie?
> 
> * Is this an Intel Mac, or one of the new M1s?
> * Did you upgrade an old OS to a new one, or transfer your files in some way?
> 
> This is the third time I've seen this issue, which means it has been happening to other users also.
> 
> My hunch is that it has something to do with Rosetta 2 and the mix of Sublime Text running as x64 and the lib being arm64.

Is an Intel Mac, I do upgrade to macOS Big Sur, but I didn't transfer any files

**Comment by debdebbie** [comment] 2021-02-05 03:21
> > Completely close the application and then open it again.
> 
> Thank you, I got it now!
> 
> startup, version: 3211 osx x64 channel: stable
> executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
> working dir: /
> packages path: /Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages
> state path: /Users/stuartchloe/Library/Application Support/Sublime Text 3/Local
> zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
> zip path: /Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages
> ignored_packages: ["Vintage"]
> pre session restore time: 0.352123
> using gpu buffer for window
> startup time: 0.858504
> environment variables loaded using: /bin/zsh -l
> reloading plugin Default.arithmetic
> reloading plugin Default.auto_indent_tag
> reloading plugin Default.block
> reloading plugin Default.colors
> reloading plugin Default.comment
> reloading plugin Default.convert_color_scheme
> reloading plugin Default.convert_syntax
> reloading plugin Default.copy_path
> reloading plugin Default.detect_indentation
> reloading plugin Default.echo
> reloading plugin Default.exec
> reloading plugin Default.fold
> reloading plugin Default.font
> reloading plugin Default.goto_line
> reloading plugin Default.history_list
> reloading plugin Default.indentation
> reloading plugin Default.install_package_control
> reloading plugin Default.kill_ring
> reloading plugin Default.mark
> reloading plugin Default.new_templates
> reloading plugin Default.open_context_url
> reloading plugin Default.open_in_browser
> reloading plugin Default.pane
> reloading plugin Default.paragraph
> reloading plugin Default.paste_from_history
> reloading plugin Default.profile
> reloading plugin Default.quick_panel
> reloading plugin Default.rename
> reloading plugin Default.run_syntax_tests
> reloading plugin Default.save_on_focus_lost
> reloading plugin Default.scroll
> reloading plugin Default.set_unsaved_view_name
> reloading plugin Default.settings
> reloading plugin Default.show_scope_name
> reloading plugin Default.side_bar
> reloading plugin Default.sort
> reloading plugin Default.switch_file
> reloading plugin Default.symbol
> reloading plugin Default.transform
> reloading plugin Default.transpose
> reloading plugin Default.ui
> reloading plugin CSS.css_completions
> reloading plugin Diff.diff
> reloading plugin HTML.encode_html_entities
> reloading plugin HTML.html_completions
> reloading plugin ShellScript.ShellScript
> reloading plugin Package Control.1_reloader
> reloading plugin Package Control.2_bootstrap
> Traceback (most recent call last):
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
> m = importlib.import_module(modulename)
> File "./python3.3/importlib/**init**.py", line 90, in import_module
> File "", line 1584, in _gcd_import
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/2_bootstrap.py", line 26, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/bootstrap.py", line 20, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 24, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/**init**.py", line 20, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/oscrypto_downloader.py", line 44, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/tls.py", line 11, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_mac/tls.py", line 39, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_mac/util.py", line 208, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_openssl/_libcrypto.py", line 15, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in
> File "./python3.3/ctypes/**init**.py", line 353, in **init**
> OSError: dlopen(/Users/stuartchloe/lib/libcrypto.dylib, 6): no suitable image found. Did find:
> /Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
> /Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
> reloading plugin Package Control.Package Control
> Traceback (most recent call last):
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
> m = importlib.import_module(modulename)
> File "./python3.3/importlib/**init**.py", line 90, in import_module
> File "", line 1584, in _gcd_import
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/Package Control.py", line 89, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/commands/**init**.py", line 3, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/commands/advanced_install_package_command.py", line 10, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 34, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/**init**.py", line 20, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/oscrypto_downloader.py", line 44, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/tls.py", line 11, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_mac/tls.py", line 39, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_mac/util.py", line 208, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_openssl/_libcrypto.py", line 15, in
> File "", line 1565, in _find_and_load
> File "", line 1532, in _find_and_load_unlocked
> File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
> exec(compile(source, source_path, 'exec'), mod.**dict**)
> File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in
> File "./python3.3/ctypes/**init**.py", line 353, in **init**
> OSError: dlopen(/Users/stuartchloe/lib/libcrypto.dylib, 6): no suitable image found. Did find:
> /Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
> /Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
> plugins loaded

@wbond any solution for my?

**Comment by KengChiChang** [comment] 2021-04-29 17:22
@debdebbie I think I had the same issue. As @wbond suggested in another thread https://github.com/wbond/package_control/issues/1515#issuecomment-766345398, I think you can just delete `/Users/stuartchloe/lib/libcrypto.dylib` and restart Sublime Text. It works for me.

**Comment by debdebbie** [comment] 2021-04-30 07:51
> @debdebbie I think I had the same issue. As @wbond suggested in another thread [#1515 (comment)](https://github.com/wbond/package_control/issues/1515#issuecomment-766345398), I think you can just delete `/Users/stuartchloe/lib/libcrypto.dylib` and restart Sublime Text. It works for me.

Thank you, it works for me too

**Comment by FichteFoll** [comment] 2021-05-22 11:32
Since the problem seems to be resolved and I don't see anything particularly actionable for PC, I'm closing this.

**Closed by FichteFoll** 2021-05-22 11:32 UTC
