### ISSUE TITLE
The following incompatible package was found installed:

### ISSUE THREAD

**Issue by zhanggang807** [wbond/package_control#1571] opened 2021-05-25 08:08 UTC
Package Control

The following incompatible package was found installed:

Pretty JSON

This is usually due to syncing packages across different machines in a way that does not check package metadata for compatibility.

Please visit https://packagecontrol.io/docs/syncing for information about how to properly sync configuration and packages across machines.

To restore package functionality, please remove each listed package and reinstall it

**Comment by rchl** [comment] 2021-05-26 21:10
You've gotten that when upgrading to ST4? In that case, after you've gotten the message, the package was upgraded to ST4-compatible version and should be working fine after restart.

You can also check the relevant #1560 issue.

**Comment by FichteFoll** [comment] 2021-05-27 02:41
Pretty JSON provides a release channel for ST4. Closing as a duplicate of #1560.

**Closed by FichteFoll** 2021-05-27 02:41 UTC
