### ISSUE TITLE
Package Control error.

### ISSUE THREAD

**Issue by fynjy1** [wbond/package_control#1353] opened 2018-04-01 00:15 UTC
I tried to instal Emmet package, but ran into trouble. Read like 20 solutions here, but everytime i get new error. Now i've no idea what should I do. Any idea? 

> DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /E/Sublime Text 3/sublime_text.exe
working dir: /E/Sublime Text 3
packages path: /E/Sublime Text 3/Data/Packages
state path: /E/Sublime Text 3/Data/Local
zip path: /E/Sublime Text 3/Packages
zip path: /E/Sublime Text 3/Data/Installed Packages
ignored_packages: []
pre session restore time: 0.0965323
startup time: 0.121532
first paint time: 0.121532
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2018-04-01 03:01:53, next run at 2018-04-01 04:01:53 or after
Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: packagecontrol.io
    issuer: US, GeoTrust Inc., RapidSSL SHA256 CA
    common name: packagecontrol.io
    issue date: Sun, 27 Nov 2016 03:00:00 GMT
    expire date: Thu, 28 Nov 2019 02:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.3.0
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: bzip2,gzip,deflate
  If-None-Match: "5ac02107-4fa5c"
  If-Modified-Since: Sun, 01 Apr 2018 00:00:07 GMT
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Sun, 01 Apr 2018 00:05:08 GMT
  Content-Type: application/json
  Last-Modified: Sun, 01 Apr 2018 00:00:07 GMT
  Connection: keep-alive
  ETag: "5ac02107-4fa5c"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from E:\Sublime Text 3\Data\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
ignored packages updated to: ["Emmet"]
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://codeload.github.com/sergeche/emmet-sublime/zip/master
  Timeout: 30
  Resolved IP: 95.213.203.78
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading package. (errno 12045) during HTTP write phase of downloading https://codeload.github.com/sergeche/emmet-sublime/zip/master.
Package Control: Download Debug
  URL: https://codeload.github.com/sergeche/emmet-sublime/zip/master
  Timeout: 30
  Resolved IP: 95.213.203.78
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at E:\Sublime Text 3\Data\Packages\User\oscrypto-ca-bundle.crt (132266 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to codeload.github.com on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at E:\Sublime Text 3\Data\Packages\User\Package Control.merged-ca-bundle
reloading /E/Sublime Text 3/Data/Packages/User/Package Control.sublime-settings
  Using hostname "codeload.github.com" for TLS SNI extension
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://codeload.github.com/sergeche/emmet-sublime/zip/master.
error: Package Control
Unable to download Emmet. Please view the console for more details.
ignored packages updated to: []
reloading /E/Sublime Text 3/Data/Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request

**Comment by dwasss** [comment] 2018-06-07 21:57
I'm on Mac OS X and had a similar problem with SSL certs. I can confirm following the steps in https://github.com/wbond/package_control/issues/1302#issuecomment-352076439 (basically deleting anything Package Control related and installing the prerelease version) I was able to finally get it to work and install packages.

**Comment by deathaxe** [comment] 2022-10-07 16:46
Closing with regards to #1302 as this error was most likely caused by encoding issues in asn1crypto.

**Closed by deathaxe** 2022-10-07 16:46 UTC
