### ISSUE TITLE
Can't install dependencies

### ISSUE THREAD

**Issue by WAnother** [wbond/package_control#1338] opened 2018-02-25 22:21 UTC
When I try to install some package, I got some dependencies error, and when I check for dependencies, here is what I got

Package Control: The dependency 'mdpopups' is not currently installed; installing...
Package Control: The dependency 'mdpopups' is not available
Package Control: The dependency 'mdpopups' could not be installed or updated
Package Control: The dependency 'pygments' is not currently installed; installing...
Package Control: The dependency 'pygments' is not available
Package Control: The dependency 'pygments' could not be installed or updated
Package Control: The dependency 'python-markdown' is not currently installed; installing...
Package Control: The dependency 'python-markdown' is not available
Package Control: The dependency 'python-markdown' could not be installed or updated
error: Package Control

One or more dependencies could not be installed or updated.

Please check the console for details.

is there a way I can manually install these?

**Comment by FichteFoll** [comment] 2018-02-26 00:18
See #1334.

**Comment by wbond** [comment] 2018-02-26 21:08
Duplicate of #1334

**Closed by wbond** 2018-02-26 21:08 UTC
