### ISSUE TITLE
Again Package Control

### ISSUE THREAD

**Issue by flopez1977** [wbond/package_control#1133] opened 2016-08-08 16:40 UTC
Hi there, I've been installing package control and the error:
Package Control
1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.

the details on the console are:
```
startup, version: 3114 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/fernandolopez/Library/Application Support/Sublime Text 3/Packages
state path: /Users/fernandolopez/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/fernandolopez/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
generating syntax summary
generating meta info summary
pre session restore time: 5.36806
using gpu buffer for window
startup time: 5.43
first paint time: 5.4417
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
plugins loaded
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading settings Packages/Package Control/Package Control.sublime-settings
reloading plugin 0_package_control_loader.00-package_control
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Installing 1 missing dependency
Package Control: Installed missing dependency bz2
Package Control: No updated packages
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.

```
I already unzip 0_package_control_loader.sublime-package, I've changed the name of bz02 to 1, after I zipped the file again, and put in the folder, but it doesn't work

sorry if you already answered into another place, I've reading and making all that Icould.
thx

**Comment by wbond** [comment] 2016-09-13 16:18
This appears to be a duplicate of #989

**Closed by wbond** 2016-09-13 16:18 UTC
