### ISSUE TITLE
There are no packages available for installation 

### ISSUE THREAD

**Issue by rays2004** [wbond/package_control#1346] opened 2018-03-10 14:34 UTC
DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /D/DEV_TOOLS/SublimeText3/sublime_text.exe
working dir: /D/DEV_TOOLS/SublimeText3
packages path: /D/DEV_TOOLS/SublimeText3/Data/Packages
state path: /D/DEV_TOOLS/SublimeText3/Data/Local
zip path: /D/DEV_TOOLS/SublimeText3/Packages
zip path: /D/DEV_TOOLS/SublimeText3/Data/Installed Packages
ignored_packages: ["Anaconda", "Vintage"]
pre session restore time: 0.11228
startup time: 0.15928
first paint time: 0.15928
Unable to fetch update url contents
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin 0_package_control_loader.00-package_control
reloading plugin AutoPEP8.sublautopep8
reloading plugin DocBlockr_Python.commands
reloading plugin DocBlockr_Python.DocblockrPython
reloading plugin DocBlockr_Python.setup
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-coffee.linter
Traceback (most recent call last):
  File "D:\DEV_TOOLS\SublimeText3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\DEV_TOOLS\SublimeText3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in D:\DEV_TOOLS\SublimeText3\Data\Installed Packages\SublimeLinter-coffee.sublime-package", line 13, in <module>
ImportError: No module named 'SublimeLinter'
reloading plugin ConvertToUTF8.ConvertToUTF8
reloading plugin IMESupport.imesupportplugin
reloading plugin Pylinter.multiconf
reloading plugin Pylinter.pylinter
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
reloading plugin SublimeTmpl.sublime-tmpl
reloading plugin Terminal.Terminal
plugins loaded
 - PyLinter: Pylint version (1, 8, 2) found

AutoPEP8:
	sublime:
	    version=3143
	    platform=windows
	    arch=x64
	    packages_path=D:\DEV_TOOLS\SublimeText3\Data\Packages
	    installed_packages_path=D:\DEV_TOOLS\SublimeText3\Data\Installed Packages
	plugin:
	    version=2.0.0
	    config: {'file_menu_search_depth': 3, 'format_on_save': False, 'global-config': '', 'list-fixes': '', 'syntax_list': ['Python'], 'exclude': None, 'debug': False, 'indent-size': 4, 'select': '', 'ignore': '', 'avoid_new_line_in_select_mode': False, 'max-line-length': 79, 'ignore-local-config': False, 'logfile': ''}

Package Control: Skipping automatic upgrade, last run at 2018-03-10 21:50:51, next run at 2018-03-10 22:50:51 or after
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02:e000:42::1
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02:e000:42::1
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at D:\DEV_TOOLS\SublimeText3\Data\Packages\User\oscrypto-ca-bundle.crt (128556 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Error downloading channel. URL error [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。 downloading https://packagecontrol.io/channel_v3.json.

**Comment by deathaxe** [comment] 2022-09-17 12:54
`WinError 10013` is most likely caused by a firewall, which blocks ST's plugin_host from accessing internet. Nothing which can be resolved by the plugin.

**Closed by deathaxe** 2022-09-17 12:54 UTC
