### ISSUE TITLE
Critical: Feature to install specific plugin versions.

### ISSUE THREAD

**Issue by joshlangner** [wbond/package_control#1349] opened 2018-03-14 16:58 UTC
This is critical for cases when key plugins are broken. SublimeLinter in particular has been pushing bad / broken updates, and won't run, but package control won't allow me to pin / install a specific version of a package that I know works.

**Comment by joshlangner** [comment] 2018-03-14 17:20
Title edits to try to sound less angry in the title :) But really frustrated by a key critical plugin that broke, and I can't work as a result.

**Comment by mdmower** [comment] 2018-03-14 17:23
You're going a bit overboard with your "Critical" title prefix, this is clearly a feature request. But yes, I would very much appreciate pinning for packages. I'm in the same boat, being irritated by the updates that came with SublimeLinter 4 and would really prefer to stick with version 3 (it's probably no surprise that a new developer is responsible for much of the muck in version 4).

**Comment by joshlangner** [comment] 2018-03-14 17:28
Hey kudos to new developers! I'm ok if they break things! (It's how we learn) ... but we always need backup options. In this case, there isn't one. Hence the "critical" :) Stuff that breaks and blocks us from using the (awesome!!) tool is pretty critical, no?

**Comment by kaste** [comment] 2018-03-14 19:14
This would also be very useful for testing. I could pin the version back and forth and see how the upgrade works. Something I just don't know how to do with current Package Control.

**Comment by FichteFoll** [comment] 2018-03-14 20:28
You can't install particular versions currently, but you can more or less pin your currently installed version by just disabling auto updates for that package.

Either way, duplicate of https://github.com/wbond/package_control/issues/938

**Closed** 2023-02-05 21:05 UTC
Labels: duplicate
