### ISSUE TITLE
Feature request: freeze a package to given version

### ISSUE THREAD

**Issue by asfaltboy** [wbond/package_control#1183] opened 2016-10-31 10:57 UTC
As mentioned in [this support thread][1]. The most straightforward use case is to allow reverting a new regressing version (empower users, drop the pressure off maintainers). 

A suggestion of an implementation would be to handle specified "frozen" versions by [skipping if same as required over here][2], otherwise re-installing the specified required version.
We could start off with a simple (documented) setting to allow freezing a given package to a given version.

Later on, we can add a new command to (re-)install a package with a given version. The command will: (1) "force install" package with given version, (2) store the frozen version (in settings?).

[1]: https://forum.sublimetext.com/t/package-control-install-specific-version-of-a-package/17394/2
[2]: https://github.com/wbond/package_control/blob/master/package_control/package_installer.py#L109-L123

**Comment by tomasdev** [comment] 2017-11-08 23:37
Kinda duplicated of https://github.com/wbond/package_control/issues/825

**Comment by FichteFoll** [comment] 2017-11-09 00:06
#825 is about dependencies only and a different beast, although it sounds similar at first.

**Comment by asfaltboy** [comment] 2018-11-21 21:08
Since it's now 2018, and some changes are upon us with PYPA doing the great work they are doing, maybe we can revisit this and implement a sort of lockfile/venv for PC, where every package could have it's own isolated environment and we rely on pip and friends to do the dependency management where possible?

Some of our options:
- https://github.com/pypa/pipenv
- https://github.com/sdispater/poetry
- https://github.com/ofek/hatch

From a use-case standpoint, I personally want to be able to easily start including wheels as deps for all supported operating systems, so that I can use optimised libraries to build top-of-the-line extensions that will leave VSCode in the dust ;)

**Comment by kylebebak** [comment] 2019-01-05 17:55
This issue seems to have morphed into #825 . In that issue I wrote about my experiment to vendor deps as @wbond suggested for my package Requester. Would love to hear what anyone thinks about it.

In the same vein as what @asfaltboy is saying, I think ST is second-to-none in terms of core functionality. But the difficulty of vendoring deps for packages, on top of the fact that outside ST Python 3.3 is sort of dead, is the only thing holding package developers back from building truly awesome packages and leaving VSCode in the dust =)

**Comment by deathaxe** [comment] 2022-09-25 19:38
Duplicate of #938

**Closed by deathaxe** 2022-09-25 19:38 UTC
