### ISSUE TITLE
There are no packages available for installation

### ISSUE THREAD

**Issue by ihomway** [wbond/package_control#1144] opened 2016-09-04 09:42 UTC
Hi,

I can't use package control recently, here is the log:
<ps: I am in China, if it is because of the GFW?>

```
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3114
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/Homway/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Error downloading channel. URL error [Errno 65] No route to host downloading https://packagecontrol.io/channel_v3.json.
```

**Comment by kaanoo2904** [comment] 2016-09-04 09:58
Maybe sth wrong with their server ? Got this error today too.

**Comment by Yuhao-Wang** [comment] 2016-09-04 10:03
I met the same problem too.

**Comment by thanapongp** [comment] 2016-09-04 10:41
Linode is under DDoS attack right now. You can check the latest status and news right here : https://status.linode.com/

**Comment by thanapongp** [comment] 2016-09-04 13:45
Looks like it's back up and running again.

**Comment by wbond** [comment] 2016-09-04 18:26
Dupe of #1143

**Closed by wbond** 2016-09-04 18:26 UTC
